name: Deploy to TrueNAS

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Вместо ubuntu-latest
    steps:
      - name: Deploy
        run: |
          cd /mnt/applications/BestPrice/api-product
          git pull origin master
          cd /mnt/applications/BestPrice
          sudo docker compose restart api-product